service: clean-cloud-cicd-dojo # NOTE: update this with your service name
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  juanfgallofunction:
    handler: src/app.handler