name: Main Workflow

on:
  push:
    branches:
      - main

jobs:

  build:
    needs: [pre-test]
    runs-on: ubuntu-latest
    steps:
      - name: Build artifact
        run: echo "Run build............"

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to AWS
        run: echo "Deploying to AWS..."

